[project]
name = "devcontainerpython"
version = "0.1.0"
description = "Google ADK Dev Container Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.3.0",
    "litellm>=1.72.6",
    "mcp[cli]>=1.9.4",
    "requests>=2.32.4",
]
